"""
ElevenLabs Streaming Text-to-Speech Engine.

Uses ElevenLabs' Flash v2.5 model for ultra-low-latency (~75ms TTFA),
human-like voice synthesis with natural tone modulation and prosody.

Supports:
- HTTP streaming: text in → audio chunks out
- Configurable voice parameters (stability, style, etc.)
- MP3 output for browser compatibility
"""

import asyncio
import logging
from typing import AsyncGenerator, Optional

import httpx

logger = logging.getLogger(__name__)

ELEVENLABS_API_URL = "https://api.elevenlabs.io/v1/text-to-speech"


class ElevenLabsTTS:
    """Streaming Text-to-Speech using ElevenLabs Flash v2.5."""

    def __init__(
        self,
        api_key: str,
        voice_id: str = "EXAVITQu4vr4xnSDxMaL",  # "Rachel"
        model_id: str = "eleven_flash_v2_5",
    ):
        """
        Args:
            api_key: ElevenLabs API key.
            voice_id: Voice ID to use (default: Rachel — warm, professional).
            model_id: Model ID (default: eleven_flash_v2_5 for lowest latency).
        """
        self.api_key = api_key
        self.voice_id = voice_id
        self.model_id = model_id

        # Voice tuning for natural, human-like "Emma" persona
        # Lower stability = more expressive, dynamic intonation
        # Higher similarity_boost = closer to base voice character
        # Style adds natural variation in delivery
        self.voice_settings = {
            "stability": 0.5,
            "similarity_boost": 0.75,
            "style": 0.3,
            "use_speaker_boost": True,
        }

        self._client: Optional[httpx.AsyncClient] = None

    async def _get_client(self) -> httpx.AsyncClient:
        """Lazy-initialize the HTTP client."""
        if self._client is None or self._client.is_closed:
            self._client = httpx.AsyncClient(
                timeout=httpx.Timeout(30.0, connect=10.0),
                limits=httpx.Limits(max_connections=5),
            )
        return self._client

    async def synthesize_stream(self, text: str) -> AsyncGenerator[bytes, None]:
        """
        Stream TTS audio chunks for the given text.

        Yields MP3 audio chunks as they are generated by ElevenLabs.
        The streaming starts as soon as the first audio is ready (~75ms).

        Args:
            text: The text to synthesize.

        Yields:
            bytes: MP3 audio chunks.
        """
        if not text or not text.strip():
            return

        client = await self._get_client()

        url = f"{ELEVENLABS_API_URL}/{self.voice_id}/stream"

        headers = {
            "xi-api-key": self.api_key,
            "Content-Type": "application/json",
            "Accept": "audio/mpeg",
        }

        payload = {
            "text": text,
            "model_id": self.model_id,
            "voice_settings": self.voice_settings,
        }

        # Query params for streaming optimization
        params = {
            "output_format": "mp3_22050_32",  # MP3 22kHz, good quality, small size
            "optimize_streaming_latency": "3",  # Aggressive latency optimization
        }

        try:
            async with client.stream(
                "POST", url, headers=headers, json=payload, params=params
            ) as response:
                if response.status_code != 200:
                    error_body = await response.aread()
                    logger.error(
                        "ElevenLabs API error %d: %s",
                        response.status_code,
                        error_body.decode("utf-8", errors="replace"),
                    )
                    return

                chunk_count = 0
                async for chunk in response.aiter_bytes(chunk_size=4096):
                    if chunk:
                        chunk_count += 1
                        yield chunk

                logger.debug(
                    "ElevenLabs TTS complete: %d chunks for %d chars",
                    chunk_count,
                    len(text),
                )

        except httpx.TimeoutException:
            logger.error("ElevenLabs TTS timeout for text: %.50s...", text)
        except httpx.ConnectError as e:
            logger.error("ElevenLabs connection error: %s", e)
        except Exception as e:
            logger.error("ElevenLabs TTS error: %s", e)

    async def synthesize(self, text: str) -> Optional[bytes]:
        """
        Synthesize complete audio for the given text.

        Collects all streaming chunks and returns the complete MP3.

        Args:
            text: The text to synthesize.

        Returns:
            Complete MP3 audio bytes, or None on failure.
        """
        chunks: list[bytes] = []
        async for chunk in self.synthesize_stream(text):
            chunks.append(chunk)

        if chunks:
            return b"".join(chunks)
        return None

    async def close(self) -> None:
        """Close the HTTP client."""
        if self._client and not self._client.is_closed:
            await self._client.aclose()
            self._client = None
        logger.info("ElevenLabs TTS client closed")
