"""
Download the approved clinic sounds (tools/ambience_sources.json) into
static/ambience/ and rewrite static/ambience/manifest.json to list them.

    python tools/fetch_ambience.py          download anything missing
    python tools/fetch_ambience.py --force  download everything again

The audio files are git-ignored; this script is how a fresh clone gets them.
Only sounds listed in ambience_sources.json (each approved by the project
owner) are ever fetched.
"""

import argparse
import json
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCES = ROOT / "tools" / "ambience_sources.json"
TARGET = ROOT / "static" / "ambience"
GROUPS = ["movement", "typing"]


def fetch(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": "Emma-clinic-demo/1.0"})
    with urllib.request.urlopen(request, timeout=60) as response:
        if response.status != 200:
            raise RuntimeError(f"HTTP {response.status}")
        kind = response.headers.get("Content-Type", "")
        data = response.read()
    if "audio" not in kind and not data[:3] == b"ID3" and not data[:2] == b"\xff\xfb":
        raise RuntimeError(f"not audio (Content-Type {kind!r})")
    if len(data) < 5_000:
        raise RuntimeError(f"suspiciously small ({len(data)} bytes)")
    return data


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--force", action="store_true", help="download even if the file exists")
    args = parser.parse_args()
    sounds = json.loads(SOURCES.read_text(encoding="utf-8"))["sounds"]
    TARGET.mkdir(parents=True, exist_ok=True)
    failed = 0
    for sound in sounds:
        path = TARGET / sound["file"]
        if path.exists() and not args.force:
            print(f"ok       {sound['file']} ({path.stat().st_size / 1e6:.2f} MB, already present)")
            continue
        try:
            data = fetch(sound["url"])
        except Exception as exc:
            failed += 1
            print(f"FAILED   {sound['file']}: {exc}")
            continue
        path.write_bytes(data)
        print(f"fetched  {sound['file']} ({len(data) / 1e6:.2f} MB) from {sound['page']}")

    manifest = {
        "_note": "Generated by tools/fetch_ambience.py from tools/ambience_sources.json. "
                 "Groups: movement (occasional door / chair / footsteps, only while Emma's line "
                 "is active) and typing. There is no background bed.",
    }
    for group in GROUPS:
        manifest[group] = [s["file"] for s in sounds if s["group"] == group and (TARGET / s["file"]).exists()]
    (TARGET / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8", newline="\n")
    print("manifest:", {g: len(manifest[g]) for g in GROUPS})
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
